version: "3.9"
volumes:
  pgdata: {}
services:
  db:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      GOOGLE_EMAIL: "${GOOGLE_EMAIL}"
      GOOGLE_PASSWORD: "${GOOGLE_PASSWORD}"
